# module:
#   imports:
#   - path: github.com/adityatelange/hugo-PaperMod

baseURL: "https://jesusnoseq.com/"
languageCode: "es-es"
title: "Jesusnoseq"
paginate: 5
theme: "hugo-PaperMod"


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: UA-35417943-1 #G-C39J2T7ZKY

minify:
  disableXML: true
  minifyOutput: true

# languages:
#     en:
#         languageName: ":en:"
#         languageAltTitle: English
#         weight: 1
#     es:
#         languageName: ":es:"
#         languageAltTitle: Español
#         weight: 2

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Jesusnoseq
  description: "Ingeniero de software especializado en backend"
  keywords: [Blog, Profile, Portfolio, Development, Software, Golang, backend, AWS]
  author: jesusnoseq
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true

  # assets:
  #   # disableHLJS: true # to disable highlight.js
  #   # disableFingerprinting: true
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  label:
    text: "Jesusnoseq"
    #icon: resources/images/prueba.png
    iconHeight: 35

  homeInfoParams:
      Title: Jesusnoseq
      Content: Ingeniero de software especializado en backend

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Jesús Rodríguez Pérez
    subtitle: "Ingeniero de software especializado en backend"
    imageUrl: "images/photo.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: jesusnoseq face photo
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  socialIcons:
    - name: github
      url: "https://github.com/jesusnoseq"
    - name: linkedin
      url: "https://www.linkedin.com/in/jesusnoseq/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/1542778/jesusnoseq"
    - name: itchio
      url: "https://jesusnoseq.itch.io/"
    - name: twitter
      url: "https://twitter.com/jesusnoseq"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true #

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  editPost:
    URL: "https://github.com/jesusnoseq/blog/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# menu:
#   main:
#     - identifier: categories
#       name: categorías
#       url: /categories/
#       weight: 10
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 20
#     - identifier: example
#       name: example.org
#       url: https://example.org
#       weight: 30


    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link


privacy:
    vimeo:
        disabled: false
        simple: true
    twitter:
        disabled: false
        enableDNT: true
        simple: true
    instagram:
        disabled: false
        simple: true
    youtube:
        disabled: false
        privacyEnhanced: true

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON